import { Component } from '@angular/core';

@Component({
  selector: 'app-gtin-form-details',
  templateUrl: './gtin-form-details.component.html',
  styleUrl: './gtin-form-details.component.scss'
})
export class GtinFormDetailsComponent {
  sampleForm = {
    "_id": "sampleid",
    "name": "Form to Capture Attr ",
    "business_requirements": "Form to Capture Attr ",
    "description": "Attribute Form",
    "components": [
        {
            "labelPosition": "left",
            "label": "Attribute Business Requirement",
            "labelWidth": "30%",
            "type": "textfield",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Attribute Business Requirement",
            "description": "This field captures the specific business need or purpose for which an attribute is being created or modified. It provides a detailed explanation of how the attribute will be used in the business context, its relevance, and the expected impact on business operations.",
            "_id": "667db973d07905836ab8d6ec",
            "field_key": "attr_bus_requirement",
            "data_type": "String",
            "code_list": null,
            "ui_element_type": "textbox",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": null,
            "status": "active",
            "min_length": 4,
            "max_length": 500,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:47.407Z",
            "updated_at": "2024-06-27T19:11:47.407Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Name (EN)",
            "labelWidth": "30%",
            "type": "textfield",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Name (EN)",
            "description": "This is the name of the attribute metadata field in english.",
            "_id": "667db975d07905836ab8d6ef",
            "field_key": "attribute_title_en",
            "data_type": "string",
            "code_list": null,
            "ui_element_type": "textbox",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 3,
            "max_length": 100,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:49.924Z",
            "updated_at": "2024-06-27T19:11:49.924Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Name (FR)",
            "labelWidth": "30%",
            "type": "textfield",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Name (FR)",
            "description": "This is the name of the attribute metadata field in French.",
            "_id": "667db976d07905836ab8d6f1",
            "field_key": "attribute_title_fr",
            "data_type": "string",
            "code_list": null,
            "ui_element_type": "textbox",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 3,
            "max_length": 100,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:50.198Z",
            "updated_at": "2024-06-27T19:11:50.198Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Description (EN)",
            "labelWidth": "30%",
            "type": "textarea",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Description (EN)",
            "description": "This is the description of the attribute metadata field in english.",
            "_id": "667db976d07905836ab8d6f3",
            "field_key": "attribute_description_en",
            "data_type": "string",
            "code_list": null,
            "ui_element_type": "textarea",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 20,
            "max_length": 500,
            "rows": 5,
            "columns": 40,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:50.473Z",
            "updated_at": "2024-06-27T19:11:50.473Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Description (FR)",
            "labelWidth": "30%",
            "type": "textarea",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Description (FR)",
            "description": "This is the description of the attribute metadata field in French.",
            "_id": "667db976d07905836ab8d6f5",
            "field_key": "attribute_description_fr",
            "data_type": "string",
            "code_list": null,
            "ui_element_type": "textarea",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 20,
            "max_length": 500,
            "rows": 5,
            "columns": 40,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:50.748Z",
            "updated_at": "2024-06-27T19:11:50.748Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Attribute Other Info",
            "labelWidth": "30%",
            "type": "textarea",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Attribute Other Info",
            "description": "This field captures any additional information or notes related to the attribute that are not covered in other fields. It allows for the inclusion of miscellaneous details that might be relevant for understanding or using the attribute effectively.",
            "_id": "667db977d07905836ab8d6f7",
            "field_key": "attribute_other_info",
            "data_type": "string",
            "code_list": null,
            "ui_element_type": "textarea",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 20,
            "max_length": 500,
            "rows": 5,
            "columns": 40,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:51.024Z",
            "updated_at": "2024-06-27T19:11:51.024Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Repeating Attribute",
            "labelWidth": "30%",
            "type": "selectbox",
            "hideLabel": false,
            "value": "",
            "values": [
                {
                    "name": "Yes",
                    "value": "true"
                }
            ],
            "layout": "",
            "field_name": "Repeating Attribute",
            "description": "This signifies the name of the repeating attribute .",
            "_id": "667db978d07905836ab8d701",
            "field_key": "repeating_attribute",
            "data_type": "boolean",
            "code_list": null,
            "ui_element_type": "textbox",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 2,
            "max_length": 30,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:52.410Z",
            "updated_at": "2024-06-27T19:11:52.410Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Min Value",
            "labelWidth": "30%",
            "type": "number",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Min Value",
            "description": "This represents the minimum value of the attribute if it's a number, and the minimum length of the attribute if it's a string.",
            "_id": "667db979d07905836ab8d709",
            "field_key": "min_value",
            "data_type": "number",
            "code_list": null,
            "ui_element_type": "textbox",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 5,
            "max_length": 1000,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:53.548Z",
            "updated_at": "2024-06-27T19:11:53.548Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Max Value",
            "labelWidth": "30%",
            "type": "number",
            "hideLabel": false,
            "value": "",
            "layout": "",
            "field_name": "Max Value",
            "description": "This represents the maximum value of the attribute if it's a number, and the minimum length of the attribute if it's a string.",
            "_id": "667db979d07905836ab8d70b",
            "field_key": "max_value",
            "data_type": "number",
            "code_list": null,
            "ui_element_type": "textbox",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 5,
            "max_length": 1000,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:53.819Z",
            "updated_at": "2024-06-27T19:11:53.819Z",
            "__v": 0,
            "required": true
        },
        {
            "labelPosition": "left",
            "label": "Data Type",
            "labelWidth": "30%",
            "type": "selectbox",
            "hideLabel": false,
            "value": "",
            "values": [
                {
                    "name": "Integer",
                    "value": "integer"
                },
                {
                    "name": "String",
                    "value": "string"
                }
            ],
            "layout": "",
            "field_name": "Data Type",
            "description": "This denotes the data type of the attribute.",
            "_id": "667db979d07905836ab8d707",
            "field_key": "data_type",
            "data_type": "string",
            "code_list": null,
            "ui_element_type": "textbox",
            "mandatory": true,
            "editable": true,
            "repeating": false,
            "data_source": "Not Applicable",
            "status": "active",
            "min_length": 5,
            "max_length": 10,
            "disabled": false,
            "hide": false,
            "created_at": "2024-06-27T19:11:53.276Z",
            "updated_at": "2024-06-27T19:11:53.276Z",
            "__v": 0,
            "required": true
        }
    ],
    "workflow_uuid": "",
    "field_key": [
        "attr_bus_requirement",
        "attribute_title_en",
        "attribute_title_fr",
        "attribute_description_en",
        "attribute_description_fr",
        "attribute_other_info",
        "repeating_attribute",
        "min_value",
        "max_value",
        "data_type"
    ],
    "created_by": "Admin",
    "updated_by": "John Doe",
    "created_at": "2024-05-15T05:30:31.544Z",
    "updated_at": "2024-05-15T05:30:31.544Z",
    "__v": 0
}

}
